# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MBE_Setting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

def Estimate_time(warm1,warm2,warm3,cool1,cool2,cool3,maxTempA,maxTempB,maxTempC,delay,anneal):
        time = 0
        time = 300/warm1 + 500/warm2 - 300/cool1-500/cool2
        time += (maxTempA-800)/warm3 - (maxTempA-800)/cool3
        time += (maxTempB-800)/warm3 - (maxTempB-800)/cool3
        time += (maxTempC-800)/warm3 - (maxTempC-800)/cool3
        time += delay + anneal
        hours, minutes= divmod(time, 60)
        string = str(int(hours))+' hours and '+str(int(minutes))+' minutes'        
        return string

class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(70, 10, 141, 21))
        self.label_55.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(140, 50, 71, 21))
        self.label_56.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_56.setObjectName("label_56")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(240, 10, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.setRange(0, 10)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setValue(8)
        
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(310, 10, 41, 21))
        self.label_57.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_57.setObjectName("label_57")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(700, 410, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.accepted.connect(self.ok_callback)
        self.buttonBox.rejected.connect(self.cancel_callback)
        
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(240, 30, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_2.setRange(0, 10)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setValue(6)
        
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(130, 30, 101, 21))
        self.label_58.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(310, 30, 41, 21))
        self.label_59.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_59.setObjectName("label_59")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(240, 50, 62, 22))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_3.setRange(0, 10)
        self.doubleSpinBox_3.setSingleStep(0.01)
        self.doubleSpinBox_3.setValue(3.5)
    
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(310, 50, 41, 21))
        self.label_60.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(140, 110, 71, 21))
        self.label_61.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(70, 70, 141, 21))
        self.label_62.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(130, 90, 111, 21))
        self.label_63.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_63.setObjectName("label_63")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(240, 70, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_4.setRange(-10, 0)
        self.doubleSpinBox_4.setSingleStep(0.01)
        self.doubleSpinBox_4.setValue(-8)
        
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(310, 70, 41, 21))
        self.label_64.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(310, 90, 41, 21))
        self.label_65.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_65.setObjectName("label_65")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(240, 90, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_5.setRange(-10, 0)
        self.doubleSpinBox_5.setSingleStep(0.01)
        self.doubleSpinBox_5.setValue(-6)
        
        self.label_66 = QtWidgets.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(310, 110, 41, 21))
        self.label_66.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_66.setObjectName("label_66")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(240, 110, 62, 22))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_6.setRange(-10, 0)
        self.doubleSpinBox_6.setSingleStep(0.01)
        self.doubleSpinBox_6.setValue(-3.5)
        
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(90, 140, 141, 21))
        self.label_67.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_67.setObjectName("label_67")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(240, 140, 62, 22))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_7.setRange(0, 100)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setValue(2)
        
        self.label_68 = QtWidgets.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(310, 140, 48, 21))
        self.label_68.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(60, 170, 151, 21))
        self.label_69.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_69.setObjectName("label_69")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(240, 170, 62, 22))
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_8.setRange(0, 500)
        self.doubleSpinBox_8.setSingleStep(1)
        self.doubleSpinBox_8.setValue(50)
        
        self.label_70 = QtWidgets.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(70, 190, 141, 21))
        self.label_70.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(310, 170, 41, 21))
        self.label_71.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_71.setObjectName("label_71")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(240, 190, 62, 22))
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_9.setRange(0, 1)
        self.doubleSpinBox_9.setSingleStep(0.01)
        self.doubleSpinBox_9.setValue(0.2)
        
        self.label_72 = QtWidgets.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(310, 190, 41, 21))
        self.label_72.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_72.setObjectName("label_72")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(225, 230, 75, 22))
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_10.setRange(0, 1500)
        self.doubleSpinBox_10.setSingleStep(0.01)
        self.doubleSpinBox_10.setValue(1004.2)
        
        
        self.label_74 = QtWidgets.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(90, 210, 121, 21))
        self.label_74.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_74.setObjectName("label_74")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(240, 210, 62, 22))
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.doubleSpinBox_11.setRange(0, 5)
        self.doubleSpinBox_11.setSingleStep(0.01)
        self.doubleSpinBox_11.setValue(3.8)
        
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(310, 210, 41, 21))
        self.label_75.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(310, 230, 41, 21))
        self.label_76.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(100, 230, 111, 21))
        self.label_77.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(10, 260, 211, 21))
        self.label_78.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_78.setObjectName("label_78")
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_12.setGeometry(QtCore.QRect(225, 260, 77, 22))
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.doubleSpinBox_12.setRange(0, 1600)
        self.doubleSpinBox_12.setSingleStep(0.1)
        self.doubleSpinBox_12.setValue(1060.2)
        
        self.label_73 = QtWidgets.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(310, 260, 41, 21))
        self.label_73.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_73.setObjectName("label_73")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(150, 280, 71, 21))
        self.label_79.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(160, 300, 71, 21))
        self.label_80.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.centralwidget)
        self.label_81.setGeometry(QtCore.QRect(160, 320, 71, 21))
        self.label_81.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_81.setObjectName("label_81")
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_13.setGeometry(QtCore.QRect(225, 280, 77, 22))
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.doubleSpinBox_13.setRange(0, 1600)
        self.doubleSpinBox_13.setSingleStep(0.1)
        self.doubleSpinBox_13.setValue(1050)
        
        self.label_82 = QtWidgets.QLabel(self.centralwidget)
        self.label_82.setGeometry(QtCore.QRect(310, 280, 41, 21))
        self.label_82.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_82.setObjectName("label_82")
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_14.setGeometry(QtCore.QRect(225, 300, 77, 22))
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.doubleSpinBox_14.setRange(0, 1600)
        self.doubleSpinBox_14.setSingleStep(0.1)
        self.doubleSpinBox_14.setValue(1430)
        
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_15.setGeometry(QtCore.QRect(225, 320, 77, 22))
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.doubleSpinBox_15.setRange(0, 1600)
        self.doubleSpinBox_15.setSingleStep(0.1)
        self.doubleSpinBox_15.setValue(1430)
        
        self.label_83 = QtWidgets.QLabel(self.centralwidget)
        self.label_83.setGeometry(QtCore.QRect(310, 300, 41, 21))
        self.label_83.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.centralwidget)
        self.label_84.setGeometry(QtCore.QRect(310, 320, 41, 21))
        self.label_84.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.centralwidget)
        self.label_85.setGeometry(QtCore.QRect(40, 350, 211, 21))
        self.label_85.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_85.setObjectName("label_85")
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_16.setGeometry(QtCore.QRect(240, 350, 62, 22))
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.doubleSpinBox_16.setRange(0, 300)
        self.doubleSpinBox_16.setSingleStep(0.1)
        self.doubleSpinBox_16.setValue(30)
        
        self.label_86 = QtWidgets.QLabel(self.centralwidget)
        self.label_86.setGeometry(QtCore.QRect(310, 350, 41, 21))
        self.label_86.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.centralwidget)
        self.label_87.setGeometry(QtCore.QRect(160, 390, 71, 21))
        self.label_87.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_87.setObjectName("label_87")
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_17.setGeometry(QtCore.QRect(240, 390, 62, 22))
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.doubleSpinBox_17.setRange(0, 300)
        self.doubleSpinBox_17.setSingleStep(0.1)
        self.doubleSpinBox_17.setValue(30)        

        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_18.setGeometry(QtCore.QRect(240, 370, 62, 22))
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.doubleSpinBox_18.setRange(0, 300)
        self.doubleSpinBox_18.setSingleStep(0.1)
        self.doubleSpinBox_18.setValue(15)   
        
        self.label_88 = QtWidgets.QLabel(self.centralwidget)
        self.label_88.setGeometry(QtCore.QRect(150, 370, 71, 21))
        self.label_88.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.centralwidget)
        self.label_89.setGeometry(QtCore.QRect(160, 410, 71, 21))
        self.label_89.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_89.setObjectName("label_89")
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_19.setGeometry(QtCore.QRect(240, 410, 62, 22))
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.doubleSpinBox_19.setRange(0, 300)
        self.doubleSpinBox_19.setSingleStep(0.1)
        self.doubleSpinBox_19.setValue(0)   
        
        self.label_90 = QtWidgets.QLabel(self.centralwidget)
        self.label_90.setGeometry(QtCore.QRect(310, 370, 41, 21))
        self.label_90.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.centralwidget)
        self.label_91.setGeometry(QtCore.QRect(310, 390, 41, 21))
        self.label_91.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.centralwidget)
        self.label_92.setGeometry(QtCore.QRect(310, 410, 41, 21))
        self.label_92.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QLabel(self.centralwidget)
        self.label_93.setGeometry(QtCore.QRect(440, 50, 71, 21))
        self.label_93.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.centralwidget)
        self.label_94.setGeometry(QtCore.QRect(430, 30, 71, 21))
        self.label_94.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_94.setObjectName("label_94")
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_20.setGeometry(QtCore.QRect(505, 10, 77, 22))
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.doubleSpinBox_20.setRange(-360, 360)
        self.doubleSpinBox_20.setSingleStep(0.1)
        self.doubleSpinBox_20.setValue(90) 
        
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_21.setGeometry(QtCore.QRect(505, 70, 77, 22))
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.doubleSpinBox_21.setRange(-360, 360)
        self.doubleSpinBox_21.setSingleStep(0.1)
        self.doubleSpinBox_21.setValue(90) 
        
        self.label_97 = QtWidgets.QLabel(self.centralwidget)
        self.label_97.setGeometry(QtCore.QRect(440, 70, 71, 21))
        self.label_97.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_97.setObjectName("label_97")
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_22.setGeometry(QtCore.QRect(505, 30, 77, 22))
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.doubleSpinBox_22.setRange(-360, 360)
        self.doubleSpinBox_22.setSingleStep(0.1)
        self.doubleSpinBox_22.setValue(90) 
        
        self.label_98 = QtWidgets.QLabel(self.centralwidget)
        self.label_98.setGeometry(QtCore.QRect(590, 10, 41, 21))
        self.label_98.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_98.setObjectName("label_98")
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_23.setGeometry(QtCore.QRect(505, 50, 77, 22))
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.doubleSpinBox_23.setRange(-360, 360)
        self.doubleSpinBox_23.setSingleStep(0.1)
        self.doubleSpinBox_23.setValue(-180) 

        self.label_100 = QtWidgets.QLabel(self.centralwidget)
        self.label_100.setGeometry(QtCore.QRect(360, 10, 211, 21))
        self.label_100.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_100.setObjectName("label_100")
        self.label_99 = QtWidgets.QLabel(self.centralwidget)
        self.label_99.setGeometry(QtCore.QRect(590, 30, 41, 21))
        self.label_99.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_99.setObjectName("label_99")
        self.label_101 = QtWidgets.QLabel(self.centralwidget)
        self.label_101.setGeometry(QtCore.QRect(590, 50, 41, 21))
        self.label_101.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(self.centralwidget)
        self.label_102.setGeometry(QtCore.QRect(590, 70, 41, 21))
        self.label_102.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.centralwidget)
        self.label_103.setGeometry(QtCore.QRect(360, 100, 211, 21))
        self.label_103.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.centralwidget)
        self.label_104.setGeometry(QtCore.QRect(390, 140, 211, 21))
        self.label_104.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_104.setObjectName("label_104")
        self.checkBox_42 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_42.setGeometry(QtCore.QRect(470, 140, 16, 18))
        self.checkBox_42.setText("")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_43.setGeometry(QtCore.QRect(510, 140, 16, 18))
        self.checkBox_43.setText("")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_44.setGeometry(QtCore.QRect(550, 140, 16, 18))
        self.checkBox_44.setText("")
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_45.setGeometry(QtCore.QRect(590, 140, 16, 18))
        self.checkBox_45.setText("")
        self.checkBox_45.setObjectName("checkBox_45")
        self.label_105 = QtWidgets.QLabel(self.centralwidget)
        self.label_105.setGeometry(QtCore.QRect(390, 170, 41, 21))
        self.label_105.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_105.setObjectName("label_105")
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_24.setGeometry(QtCore.QRect(480, 170, 62, 22))
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.doubleSpinBox_24.setRange(0, 360)
        self.doubleSpinBox_24.setSingleStep(0.1)
        self.doubleSpinBox_24.setValue(90) 
        
        self.label_95 = QtWidgets.QLabel(self.centralwidget)
        self.label_95.setGeometry(QtCore.QRect(550, 170, 41, 21))
        self.label_95.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_95.setObjectName("label_95")
        self.label_106 = QtWidgets.QLabel(self.centralwidget)
        self.label_106.setGeometry(QtCore.QRect(390, 210, 211, 21))
        self.label_106.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_106.setObjectName("label_106")
        self.checkBox_46 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_46.setGeometry(QtCore.QRect(470, 210, 16, 18))
        self.checkBox_46.setText("")
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_47 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_47.setGeometry(QtCore.QRect(550, 210, 16, 18))
        self.checkBox_47.setText("")
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_48 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_48.setGeometry(QtCore.QRect(590, 210, 16, 18))
        self.checkBox_48.setText("")
        self.checkBox_48.setObjectName("checkBox_48")
        self.checkBox_49 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_49.setGeometry(QtCore.QRect(510, 210, 16, 18))
        self.checkBox_49.setText("")
        self.checkBox_49.setObjectName("checkBox_49")
        
                # calling the uncheck method if any check box state is changed
        self.checkBox_46.stateChanged.connect(self.uncheck)
        self.checkBox_47.stateChanged.connect(self.uncheck)
        self.checkBox_48.stateChanged.connect(self.uncheck)
        self.checkBox_49.stateChanged.connect(self.uncheck)
        
        self.label_107 = QtWidgets.QLabel(self.centralwidget)
        self.label_107.setGeometry(QtCore.QRect(370, 250, 211, 21))
        self.label_107.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_107.setObjectName("label_107")
        self.label_108 = QtWidgets.QLabel(self.centralwidget)
        self.label_108.setGeometry(QtCore.QRect(400, 270, 121, 21))
        self.label_108.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_108.setObjectName("label_108")
        self.label_96 = QtWidgets.QLabel(self.centralwidget)
        self.label_96.setGeometry(QtCore.QRect(410, 290, 111, 21))
        self.label_96.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_96.setObjectName("label_96")
        self.label_109 = QtWidgets.QLabel(self.centralwidget)
        self.label_109.setGeometry(QtCore.QRect(580, 290, 41, 21))
        self.label_109.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_109.setObjectName("label_109")
        self.label_110 = QtWidgets.QLabel(self.centralwidget)
        self.label_110.setGeometry(QtCore.QRect(580, 270, 41, 21))
        self.label_110.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_110.setObjectName("label_110")
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_25.setGeometry(QtCore.QRect(510, 290, 62, 22))
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.doubleSpinBox_25.setRange(0, 5)
        self.doubleSpinBox_25.setSingleStep(0.01)
        self.doubleSpinBox_25.setValue(3.8)
        
        
        self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_26.setGeometry(QtCore.QRect(495, 270, 77, 22))
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.doubleSpinBox_26.setRange(0, 1500)
        self.doubleSpinBox_26.setSingleStep(0.01)
        self.doubleSpinBox_26.setValue(1004.2)

        self.label_111 = QtWidgets.QLabel(self.centralwidget)
        self.label_111.setGeometry(QtCore.QRect(390, 310, 111, 21))
        self.label_111.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_111.setObjectName("label_111")
        self.doubleSpinBox_27 = QtWidgets.QSpinBox(self.centralwidget)
        self.doubleSpinBox_27.setGeometry(QtCore.QRect(510, 310, 62, 22))
        self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
        self.doubleSpinBox_27.setRange(0, 999)
        self.doubleSpinBox_27.setSingleStep(1)
        self.doubleSpinBox_27.setValue(720)   
        
        self.label_112 = QtWidgets.QLabel(self.centralwidget)
        self.label_112.setGeometry(QtCore.QRect(580, 310, 41, 21))
        self.label_112.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_112.setObjectName("label_112")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 360, 181, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_113 = QtWidgets.QLabel(self.centralwidget)
        self.label_113.setGeometry(QtCore.QRect(510, 120, 16, 21))
        self.label_113.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QLabel(self.centralwidget)
        self.label_114.setGeometry(QtCore.QRect(470, 120, 16, 21))
        self.label_114.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.centralwidget)
        self.label_115.setGeometry(QtCore.QRect(550, 120, 16, 21))
        self.label_115.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(self.centralwidget)
        self.label_116.setGeometry(QtCore.QRect(590, 120, 16, 21))
        self.label_116.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_116.setObjectName("label_116")
        self.label_117 = QtWidgets.QLabel(self.centralwidget)
        self.label_117.setGeometry(QtCore.QRect(510, 190, 16, 21))
        self.label_117.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(self.centralwidget)
        self.label_118.setGeometry(QtCore.QRect(590, 190, 16, 21))
        self.label_118.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_118.setObjectName("label_118")
        self.label_119 = QtWidgets.QLabel(self.centralwidget)
        self.label_119.setGeometry(QtCore.QRect(550, 190, 16, 21))
        self.label_119.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_119.setObjectName("label_119")
        self.label_120 = QtWidgets.QLabel(self.centralwidget)
        self.label_120.setGeometry(QtCore.QRect(470, 190, 16, 21))
        self.label_120.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_120.setObjectName("label_120")
        self.label_121 = QtWidgets.QLabel(self.centralwidget)
        self.label_121.setGeometry(QtCore.QRect(490, 230, 51, 21))
        self.label_121.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_121.setObjectName("label_121")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(630, 390, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 390, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_122 = QtWidgets.QLabel(self.centralwidget)
        self.label_122.setGeometry(QtCore.QRect(350, 350, 211, 21))
        self.label_122.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_122.setObjectName("label_122")
        self.label_123 = QtWidgets.QLabel(self.centralwidget)
        self.label_123.setGeometry(QtCore.QRect(360, 380, 201, 21))
        self.label_123.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_123.setObjectName("label_123")
        self.doubleSpinBox_28 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_28.setGeometry(QtCore.QRect(510, 380, 62, 22))
        self.doubleSpinBox_28.setObjectName("doubleSpinBox_28")
        self.checkBox_50 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_50.setGeometry(QtCore.QRect(500, 360, 16, 18))
        self.checkBox_50.setText("")
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_51 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_51.setGeometry(QtCore.QRect(540, 360, 16, 18))
        self.checkBox_51.setText("")
        self.checkBox_51.setObjectName("checkBox_51")
        self.label_124 = QtWidgets.QLabel(self.centralwidget)
        self.label_124.setGeometry(QtCore.QRect(540, 340, 16, 21))
        self.label_124.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_124.setObjectName("label_124")
        self.label_125 = QtWidgets.QLabel(self.centralwidget)
        self.label_125.setGeometry(QtCore.QRect(620, 340, 16, 21))
        self.label_125.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_125.setObjectName("label_125")
        self.checkBox_52 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_52.setGeometry(QtCore.QRect(580, 360, 16, 18))
        self.checkBox_52.setText("")
        self.checkBox_52.setObjectName("checkBox_52")
        self.label_126 = QtWidgets.QLabel(self.centralwidget)
        self.label_126.setGeometry(QtCore.QRect(500, 340, 16, 21))
        self.label_126.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_126.setObjectName("label_126")
        self.checkBox_53 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_53.setGeometry(QtCore.QRect(620, 360, 16, 18))
        self.checkBox_53.setText("")
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkBox_50.stateChanged.connect(self.uncheck_2)
        self.checkBox_51.stateChanged.connect(self.uncheck_2)
        self.checkBox_52.stateChanged.connect(self.uncheck_2)
        self.checkBox_53.stateChanged.connect(self.uncheck_2)
        
        
        self.label_127 = QtWidgets.QLabel(self.centralwidget)
        self.label_127.setGeometry(QtCore.QRect(580, 340, 16, 21))
        self.label_127.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_127.setObjectName("label_127")
        self.label_128 = QtWidgets.QLabel(self.centralwidget)
        self.label_128.setGeometry(QtCore.QRect(380, 400, 201, 21))
        self.label_128.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.centralwidget)
        self.label_129.setGeometry(QtCore.QRect(580, 380, 41, 21))
        self.label_129.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_129.setObjectName("label_129")
        self.doubleSpinBox_29 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_29.setGeometry(QtCore.QRect(510, 400, 62, 22))
        self.doubleSpinBox_29.setObjectName("doubleSpinBox_29")
        self.label_130 = QtWidgets.QLabel(self.centralwidget)
        self.label_130.setGeometry(QtCore.QRect(580, 400, 41, 21))
        self.label_130.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_130.setObjectName("label_130")
        self.label_131 = QtWidgets.QLabel(self.centralwidget)
        self.label_131.setGeometry(QtCore.QRect(380, 420, 201, 21))
        self.label_131.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_131.setObjectName("label_131")
        self.doubleSpinBox_30 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_30.setGeometry(QtCore.QRect(510, 420, 62, 22))
        self.doubleSpinBox_30.setObjectName("doubleSpinBox_30")
        self.label_132 = QtWidgets.QLabel(self.centralwidget)
        self.label_132.setGeometry(QtCore.QRect(580, 420, 41, 21))
        self.label_132.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_132.setObjectName("label_132")
        self.label_133 = QtWidgets.QLabel(self.centralwidget)
        self.label_133.setGeometry(QtCore.QRect(760, 50, 71, 21))
        self.label_133.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_133.setObjectName("label_133")
        self.doubleSpinBox_31 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_31.setGeometry(QtCore.QRect(830, 30, 62, 22))
        self.doubleSpinBox_31.setObjectName("doubleSpinBox_31")
        self.doubleSpinBox_32 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_32.setGeometry(QtCore.QRect(830, 50, 62, 22))
        self.doubleSpinBox_32.setObjectName("doubleSpinBox_32")
        self.doubleSpinBox_33 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_33.setGeometry(QtCore.QRect(830, 10, 62, 22))
        self.doubleSpinBox_33.setObjectName("doubleSpinBox_33")
        self.label_134 = QtWidgets.QLabel(self.centralwidget)
        self.label_134.setGeometry(QtCore.QRect(630, 10, 211, 21))
        self.label_134.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_134.setObjectName("label_134")
        self.label_135 = QtWidgets.QLabel(self.centralwidget)
        self.label_135.setGeometry(QtCore.QRect(760, 70, 71, 21))
        self.label_135.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_135.setObjectName("label_135")
        self.doubleSpinBox_34 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_34.setGeometry(QtCore.QRect(830, 70, 62, 22))
        self.doubleSpinBox_34.setObjectName("doubleSpinBox_34")
        self.label_136 = QtWidgets.QLabel(self.centralwidget)
        self.label_136.setGeometry(QtCore.QRect(750, 30, 71, 21))
        self.label_136.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_136.setObjectName("label_136")
        self.label_137 = QtWidgets.QLabel(self.centralwidget)
        self.label_137.setGeometry(QtCore.QRect(900, 30, 16, 21))
        self.label_137.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_137.setObjectName("label_137")
        self.label_138 = QtWidgets.QLabel(self.centralwidget)
        self.label_138.setGeometry(QtCore.QRect(900, 10, 16, 21))
        self.label_138.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_138.setObjectName("label_138")
        self.label_139 = QtWidgets.QLabel(self.centralwidget)
        self.label_139.setGeometry(QtCore.QRect(900, 70, 16, 21))
        self.label_139.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_139.setObjectName("label_139")
        self.label_140 = QtWidgets.QLabel(self.centralwidget)
        self.label_140.setGeometry(QtCore.QRect(900, 50, 16, 21))
        self.label_140.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_140.setObjectName("label_140")
        self.label_141 = QtWidgets.QLabel(self.centralwidget)
        self.label_141.setGeometry(QtCore.QRect(630, 100, 151, 21))
        self.label_141.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_141.setObjectName("label_141")
        self.label_142 = QtWidgets.QLabel(self.centralwidget)
        self.label_142.setGeometry(QtCore.QRect(720, 120, 151, 21))
        self.label_142.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_142.setObjectName("label_142")
        self.label_144 = QtWidgets.QLabel(self.centralwidget)
        self.label_144.setGeometry(QtCore.QRect(900, 120, 151, 21))
        self.label_144.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_144.setObjectName("label_144")
        self.doubleSpinBox_35 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_35.setGeometry(QtCore.QRect(820, 120, 75, 22))
        self.doubleSpinBox_35.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_35.setRange(0, 1500)
        self.doubleSpinBox_35.setSingleStep(0.01)
        self.doubleSpinBox_35.setValue(1004.2)
        self.label_143 = QtWidgets.QLabel(self.centralwidget)
        self.label_143.setGeometry(QtCore.QRect(720, 140, 151, 21))
        self.label_143.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_143.setObjectName("label_143")
        self.label_145 = QtWidgets.QLabel(self.centralwidget)
        self.label_145.setGeometry(QtCore.QRect(900, 140, 151, 21))
        self.label_145.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_145.setObjectName("label_145")
        self.doubleSpinBox_36 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_36.setGeometry(QtCore.QRect(820, 140, 75, 22))
        self.doubleSpinBox_36.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_36.setRange(0, 6)
        self.doubleSpinBox_36.setSingleStep(0.01)
        self.doubleSpinBox_36.setValue(2.6)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Growth Setting"))
        self.label_55.setText(_translate("MainWindow", "Heating rate (<300 K) ="))
        self.label_56.setText(_translate("MainWindow", " (>800 K) ="))
        self.label_57.setText(_translate("MainWindow", "K/min"))
        self.label_58.setText(_translate("MainWindow", "(300-800 K) ="))
        self.label_59.setText(_translate("MainWindow", "K/min"))
        self.label_60.setText(_translate("MainWindow", "K/min"))
        self.label_61.setText(_translate("MainWindow", "(>800 K) ="))
        self.label_62.setText(_translate("MainWindow", "Cooling rate (<300 K) ="))
        self.label_63.setText(_translate("MainWindow", "(300-800 K) ="))
        self.label_64.setText(_translate("MainWindow", "K/min"))
        self.label_65.setText(_translate("MainWindow", "K/min"))
        self.label_66.setText(_translate("MainWindow", "K/min"))
        self.label_67.setText(_translate("MainWindow", "Pressure threshold = "))
        self.label_68.setText(_translate("MainWindow", "e-9 mbar"))
        self.label_69.setText(_translate("MainWindow", "Ion Beam rate (V/min) = "))
        self.label_70.setText(_translate("MainWindow", "Filament rate (I/min) = "))
        self.label_71.setText(_translate("MainWindow", "V/min"))
        self.label_72.setText(_translate("MainWindow", "A/min"))
        self.label_74.setText(_translate("MainWindow", "Ion Beam max (V) = "))
        self.label_75.setText(_translate("MainWindow", "V"))
        self.label_76.setText(_translate("MainWindow", "A"))
        self.label_77.setText(_translate("MainWindow", "Filament max (I) = "))
        self.label_78.setText(_translate("MainWindow", "Shutter open temperature (A/Sn) ="))
        self.label_73.setText(_translate("MainWindow", "K"))
        self.label_79.setText(_translate("MainWindow", "(B/BeF2) ="))
        self.label_80.setText(_translate("MainWindow", "(C/Co) ="))
        self.label_81.setText(_translate("MainWindow", "(D/Fe) ="))
        self.label_82.setText(_translate("MainWindow", "K"))
        self.label_83.setText(_translate("MainWindow", "K"))
        self.label_84.setText(_translate("MainWindow", "K"))
        self.label_85.setText(_translate("MainWindow", "Shutter opening time (A/Sn) ="))
        self.label_86.setText(_translate("MainWindow", "min"))
        self.label_87.setText(_translate("MainWindow", "(C/Co) ="))
        self.label_88.setText(_translate("MainWindow", "(B/BeF2) ="))
        self.label_89.setText(_translate("MainWindow", "(D/Fe) ="))
        self.label_90.setText(_translate("MainWindow", "min"))
        self.label_91.setText(_translate("MainWindow", "min"))
        self.label_92.setText(_translate("MainWindow", "min"))
        self.label_93.setText(_translate("MainWindow", "(C/Co) ="))
        self.label_94.setText(_translate("MainWindow", "(B/BeF2) ="))
        self.label_97.setText(_translate("MainWindow", "(D/Fe) ="))
        self.label_98.setText(_translate("MainWindow", "deg"))
        self.label_100.setText(_translate("MainWindow", "Shutter angle (A/Sn) ="))
        self.label_99.setText(_translate("MainWindow", "deg"))
        self.label_101.setText(_translate("MainWindow", "deg"))
        self.label_102.setText(_translate("MainWindow", "deg"))
        self.label_103.setText(_translate("MainWindow", "Shutter open-close sequences"))
        self.label_104.setText(_translate("MainWindow", "Growth"))
        self.label_105.setText(_translate("MainWindow", "Delay"))
        self.label_95.setText(_translate("MainWindow", "min"))
        self.label_106.setText(_translate("MainWindow", "Capping"))
        self.label_107.setText(_translate("MainWindow", "Annealing process"))
        self.label_108.setText(_translate("MainWindow", "Ion Beam (V) = "))
        self.label_96.setText(_translate("MainWindow", "Filament (I) = "))
        self.label_109.setText(_translate("MainWindow", "A"))
        self.label_110.setText(_translate("MainWindow", "V"))
        self.label_111.setText(_translate("MainWindow", "Annealing time = "))
        self.label_112.setText(_translate("MainWindow", "min"))
        self.pushButton.setText(_translate("MainWindow", "Save as .txt"))
        self.label_113.setText(_translate("MainWindow", "B"))
        self.label_114.setText(_translate("MainWindow", "A"))
        self.label_115.setText(_translate("MainWindow", "C"))
        self.label_116.setText(_translate("MainWindow", "D"))
        self.label_117.setText(_translate("MainWindow", "B"))
        self.label_118.setText(_translate("MainWindow", "D"))
        self.label_119.setText(_translate("MainWindow", "C"))
        self.label_120.setText(_translate("MainWindow", "A"))
        self.label_121.setText(_translate("MainWindow", "Finished!"))
        self.label.setText(_translate("MainWindow", "Estimated finish time"))
        self.label_2.setText(_translate("MainWindow", Estimate_time(8,6,3.5,-8,-6,-3.5,1430,1060,800,10,720)))
        self.label_122.setText(_translate("MainWindow", "Calibration process"))
        self.label_123.setText(_translate("MainWindow", "Starting Temperature ="))
        self.label_124.setText(_translate("MainWindow", "B"))
        self.label_125.setText(_translate("MainWindow", "D"))
        self.label_126.setText(_translate("MainWindow", "A"))
        self.label_127.setText(_translate("MainWindow", "C"))
        self.label_128.setText(_translate("MainWindow", "Temperature step = "))
        self.label_129.setText(_translate("MainWindow", "K"))
        self.label_130.setText(_translate("MainWindow", "K"))
        self.label_131.setText(_translate("MainWindow", "Shutter delay = "))
        self.label_132.setText(_translate("MainWindow", "s"))
        self.label_133.setText(_translate("MainWindow", "(C/Co) ="))
        self.label_134.setText(_translate("MainWindow", "Max degas temperature (A/Sn) ="))
        self.label_135.setText(_translate("MainWindow", "(D/Fe) ="))
        self.label_136.setText(_translate("MainWindow", "(B/BeF2) ="))
        self.label_137.setText(_translate("MainWindow", "K"))
        self.label_138.setText(_translate("MainWindow", "K"))
        self.label_139.setText(_translate("MainWindow", "K"))
        self.label_140.setText(_translate("MainWindow", "K"))
        self.label_141.setText(_translate("MainWindow", "Substrate temperature"))
        self.label_142.setText(_translate("MainWindow", "Ion Beam (V) = "))
        self.label_143.setText(_translate("MainWindow", "Filament (I) = "))
        self.label_144.setText(_translate("MainWindow", "V"))
        self.label_145.setText(_translate("MainWindow", "A"))
        
    def uncheck(self, state):
        # checking if state is checked
        if state == Qt.Checked:
            # if first check box is selected
            if self.MainWindow.sender() == self.checkBox_46:
                # making other check box to uncheck
                self.checkBox_47.setChecked(False)
                self.checkBox_48.setChecked(False)
                self.checkBox_49.setChecked(False)
            # if second check box is selected
            elif self.MainWindow.sender() == self.checkBox_47:
                # making other check box to uncheck
                self.checkBox_46.setChecked(False)
                self.checkBox_48.setChecked(False)
                self.checkBox_49.setChecked(False)
            # if third check box is selected
            elif self.MainWindow.sender() == self.checkBox_48:
                # making other check box to uncheck
                self.checkBox_46.setChecked(False)
                self.checkBox_47.setChecked(False)
                self.checkBox_49.setChecked(False)
            # if fourth check box is selected
            elif self.MainWindow.sender() == self.checkBox_49:
                # making other check box to uncheck
                self.checkBox_46.setChecked(False)
                self.checkBox_47.setChecked(False)
                self.checkBox_48.setChecked(False)
    
    def uncheck_2(self, state):
        # checking if state is checked
        if state == Qt.Checked:
            # if first check box is selected
            if self.MainWindow.sender() == self.checkBox_50:
                # making other check box to uncheck
                self.checkBox_51.setChecked(False)
                self.checkBox_52.setChecked(False)
                self.checkBox_53.setChecked(False)
            # if second check box is selected
            elif self.MainWindow.sender() == self.checkBox_51:
                # making other check box to uncheck
                self.checkBox_50.setChecked(False)
                self.checkBox_52.setChecked(False)
                self.checkBox_53.setChecked(False)
            # if third check box is selected
            elif self.MainWindow.sender() == self.checkBox_52:
                # making other check box to uncheck
                self.checkBox_50.setChecked(False)
                self.checkBox_51.setChecked(False)
                self.checkBox_53.setChecked(False)
            # if fourth check box is selected
            elif self.MainWindow.sender() == self.checkBox_53:
                # making other check box to uncheck
                self.checkBox_50.setChecked(False)
                self.checkBox_51.setChecked(False)
                self.checkBox_52.setChecked(False) 
                
    def ok_callback(self):
        print("OK")
        self.MainWindow.close()
        
    def cancel_callback(self):
        print("Cancel")
        self.MainWindow.close()
    
    def write_output(self):
        print("Output written!")
        self.MainWindow.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



