# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nanoscale_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import MBE_Setting
from MBE_Setting import Ui_MainWindow_2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(540, 180, 101, 16))
        self.label_33.setObjectName("label_33")
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_27.setGeometry(QtCore.QRect(660, 220, 16, 18))
        self.checkBox_27.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_27.setText("")
        self.checkBox_27.setObjectName("checkBox_27")
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(680, 200, 121, 16))
        self.label_43.setObjectName("label_43")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(180, 460, 61, 16))
        self.label_24.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_5.setGeometry(QtCore.QRect(240, 200, 71, 31))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_9.setGeometry(QtCore.QRect(370, 420, 16, 18))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(410, 180, 81, 16))
        self.label_31.setObjectName("label_31")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_19.setGeometry(QtCore.QRect(520, 180, 16, 18))
        self.checkBox_19.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(200, 130, 47, 14))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 70, 61, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_13.setGeometry(QtCore.QRect(390, 180, 16, 18))
        self.checkBox_13.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(320, 500, 47, 16))
        self.label_37.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(680, 220, 121, 16))
        self.label_46.setObjectName("label_46")
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(410, 200, 91, 16))
        self.label_41.setObjectName("label_41")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_16.setGeometry(QtCore.QRect(390, 240, 16, 18))
        self.checkBox_16.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_6.setGeometry(QtCore.QRect(240, 240, 71, 31))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_17.setGeometry(QtCore.QRect(390, 260, 16, 18))
        self.checkBox_17.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(320, 130, 47, 14))
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(540, 200, 111, 16))
        self.label_42.setObjectName("label_42")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_21.setGeometry(QtCore.QRect(520, 220, 16, 18))
        self.checkBox_21.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(200, 420, 47, 14))
        self.label_27.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(200, 340, 47, 14))
        self.label_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(480, 20, 221, 16))
        self.label_13.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(340, 50, 16, 18))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(200, 250, 47, 14))
        self.label_11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(210, 10, 121, 21))
        self.label_18.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(200, 170, 47, 14))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(320, 170, 47, 14))
        self.label_8.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(180, 500, 61, 16))
        self.label_38.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_38.setObjectName("label_38")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_8.setGeometry(QtCore.QRect(370, 460, 16, 18))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(410, 220, 121, 16))
        self.label_44.setObjectName("label_44")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(340, 170, 16, 18))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_29.setGeometry(QtCore.QRect(660, 260, 16, 18))
        self.checkBox_29.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_29.setText("")
        self.checkBox_29.setObjectName("checkBox_29")
        self.label_48 = QtWidgets.QLabel(self.tab)
        self.label_48.setGeometry(QtCore.QRect(540, 240, 121, 16))
        self.label_48.setObjectName("label_48")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(500, 50, 47, 14))
        self.label_15.setObjectName("label_15")
        self.label_49 = QtWidgets.QLabel(self.tab)
        self.label_49.setGeometry(QtCore.QRect(680, 240, 121, 16))
        self.label_49.setObjectName("label_49")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(180, 380, 81, 16))
        self.label_22.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_8.setGeometry(QtCore.QRect(240, 450, 71, 31))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(540, 160, 111, 16))
        self.label_32.setObjectName("label_32")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(320, 210, 47, 14))
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_10.setGeometry(QtCore.QRect(240, 410, 71, 31))
        self.lcdNumber_10.setStyleSheet("")
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(530, 130, 141, 21))
        self.label_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(320, 50, 47, 14))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(400, 300, 391, 251))
        self.label_28.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("../Pictures/MBE.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_4.setGeometry(QtCore.QRect(240, 160, 71, 31))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(320, 420, 47, 14))
        self.label_29.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_3.setGeometry(QtCore.QRect(240, 120, 71, 31))
        self.lcdNumber_3.setStyleSheet("")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(600, 70, 41, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(200, 210, 47, 14))
        self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_23.setGeometry(QtCore.QRect(520, 260, 16, 18))
        self.checkBox_23.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(320, 90, 47, 14))
        self.label_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 90, 16, 18))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(230, 300, 81, 21))
        self.label_19.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(370, 340, 16, 18))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(320, 250, 47, 14))
        self.label_12.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(450, 70, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(200, 90, 47, 14))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(680, 160, 71, 16))
        self.label_34.setObjectName("label_34")
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_28.setGeometry(QtCore.QRect(660, 240, 16, 18))
        self.checkBox_28.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_28.setText("")
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(340, 210, 16, 18))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(540, 220, 121, 16))
        self.label_45.setObjectName("label_45")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_15.setGeometry(QtCore.QRect(390, 220, 16, 18))
        self.checkBox_15.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_25.setGeometry(QtCore.QRect(660, 180, 16, 18))
        self.checkBox_25.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_25.setText("")
        self.checkBox_25.setObjectName("checkBox_25")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(680, 180, 71, 16))
        self.label_35.setObjectName("label_35")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_18.setGeometry(QtCore.QRect(520, 160, 16, 18))
        self.checkBox_18.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_10.setGeometry(QtCore.QRect(370, 380, 16, 18))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(500, 70, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(240, 40, 71, 31))
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 130, 16, 18))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(410, 240, 121, 16))
        self.label_47.setObjectName("label_47")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_20.setGeometry(QtCore.QRect(520, 200, 16, 18))
        self.checkBox_20.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(540, 260, 91, 16))
        self.label_40.setObjectName("label_40")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_7.setGeometry(QtCore.QRect(240, 330, 71, 31))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_12.setGeometry(QtCore.QRect(390, 160, 16, 18))
        self.checkBox_12.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_24.setGeometry(QtCore.QRect(660, 160, 16, 18))
        self.checkBox_24.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_26.setGeometry(QtCore.QRect(660, 200, 16, 18))
        self.checkBox_26.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_26.setText("")
        self.checkBox_26.setObjectName("checkBox_26")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(680, 260, 111, 16))
        self.label_36.setObjectName("label_36")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_14.setGeometry(QtCore.QRect(390, 200, 16, 18))
        self.checkBox_14.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_22.setGeometry(QtCore.QRect(520, 240, 16, 18))
        self.checkBox_22.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.label_50 = QtWidgets.QLabel(self.tab)
        self.label_50.setGeometry(QtCore.QRect(410, 260, 61, 16))
        self.label_50.setObjectName("label_50")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(200, 50, 47, 14))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setGeometry(QtCore.QRect(710, 180, 111, 16))
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 171, 541))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../Pictures/STM.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_9.setGeometry(QtCore.QRect(240, 370, 71, 31))
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(320, 380, 47, 14))
        self.label_26.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(550, 50, 47, 14))
        self.label_16.setObjectName("label_16")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_11.setGeometry(QtCore.QRect(370, 500, 16, 18))
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(320, 340, 47, 14))
        self.label_25.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_25.setObjectName("label_25")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setGeometry(QtCore.QRect(340, 250, 16, 18))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(320, 460, 47, 14))
        self.label_30.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_11.setGeometry(QtCore.QRect(240, 490, 71, 31))
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_2.setGeometry(QtCore.QRect(240, 80, 71, 31))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(450, 50, 47, 14))
        self.label_14.setObjectName("label_14")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_3.setGeometry(QtCore.QRect(550, 70, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(410, 160, 47, 14))
        self.label_23.setObjectName("label_23")
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(410, 280, 101, 16))
        self.label_53.setObjectName("label_53")
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_30.setGeometry(QtCore.QRect(390, 280, 16, 18))
        self.checkBox_30.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_30.setText("")
        self.checkBox_30.setObjectName("checkBox_30")
        self.label_54 = QtWidgets.QLabel(self.tab)
        self.label_54.setGeometry(QtCore.QRect(540, 280, 141, 16))
        self.label_54.setObjectName("label_54")
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_31.setGeometry(QtCore.QRect(520, 280, 16, 18))
        self.checkBox_31.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : red;\n"
"}")
        self.checkBox_31.setText("")
        self.checkBox_31.setObjectName("checkBox_31")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        self.label_55.setGeometry(QtCore.QRect(140, 0, 81, 21))
        self.label_55.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_3)
        self.label_56.setGeometry(QtCore.QRect(80, 40, 47, 14))
        self.label_56.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_3)
        self.label_57.setGeometry(QtCore.QRect(200, 120, 47, 16))
        self.label_57.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_57.setObjectName("label_57")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_12.setGeometry(QtCore.QRect(120, 110, 71, 31))
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.label_58 = QtWidgets.QLabel(self.tab_3)
        self.label_58.setGeometry(QtCore.QRect(60, 80, 61, 16))
        self.label_58.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_58.setObjectName("label_58")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_13.setGeometry(QtCore.QRect(120, 70, 71, 31))
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_14.setGeometry(QtCore.QRect(120, 30, 71, 31))
        self.lcdNumber_14.setStyleSheet("")
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        self.label_59.setGeometry(QtCore.QRect(200, 40, 47, 14))
        self.label_59.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_59.setObjectName("label_59")
        self.checkBox_32 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_32.setGeometry(QtCore.QRect(250, 40, 16, 18))
        self.checkBox_32.setText("")
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_33 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_33.setGeometry(QtCore.QRect(250, 80, 16, 18))
        self.checkBox_33.setText("")
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_34 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_34.setGeometry(QtCore.QRect(250, 120, 16, 18))
        self.checkBox_34.setText("")
        self.checkBox_34.setObjectName("checkBox_34")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(60, 120, 61, 16))
        self.label_60.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(200, 80, 47, 14))
        self.label_61.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        self.label_62.setGeometry(QtCore.QRect(60, 150, 241, 21))
        self.label_62.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_62.setObjectName("label_62")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_15.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.lcdNumber_15.setStyleSheet("")
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_16.setGeometry(QtCore.QRect(100, 180, 71, 31))
        self.lcdNumber_16.setStyleSheet("")
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_17.setGeometry(QtCore.QRect(180, 180, 71, 31))
        self.lcdNumber_17.setStyleSheet("")
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_18.setGeometry(QtCore.QRect(260, 180, 71, 31))
        self.lcdNumber_18.setStyleSheet("")
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.label_63 = QtWidgets.QLabel(self.tab_3)
        self.label_63.setGeometry(QtCore.QRect(480, 0, 221, 31))
        self.label_63.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        self.label_64.setGeometry(QtCore.QRect(90, 220, 171, 21))
        self.label_64.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_64.setObjectName("label_64")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_19.setGeometry(QtCore.QRect(20, 250, 71, 31))
        self.lcdNumber_19.setStyleSheet("")
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_20.setGeometry(QtCore.QRect(20, 280, 71, 31))
        self.lcdNumber_20.setStyleSheet("")
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_21.setGeometry(QtCore.QRect(100, 250, 71, 31))
        self.lcdNumber_21.setStyleSheet("")
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_22.setGeometry(QtCore.QRect(100, 280, 71, 31))
        self.lcdNumber_22.setStyleSheet("")
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_23.setGeometry(QtCore.QRect(180, 250, 71, 31))
        self.lcdNumber_23.setStyleSheet("")
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.lcdNumber_24 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_24.setGeometry(QtCore.QRect(180, 280, 71, 31))
        self.lcdNumber_24.setStyleSheet("")
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.lcdNumber_25 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_25.setGeometry(QtCore.QRect(260, 250, 71, 31))
        self.lcdNumber_25.setStyleSheet("")
        self.lcdNumber_25.setObjectName("lcdNumber_25")
        self.lcdNumber_26 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_26.setGeometry(QtCore.QRect(260, 280, 71, 31))
        self.lcdNumber_26.setStyleSheet("")
        self.lcdNumber_26.setObjectName("lcdNumber_26")
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        self.label_65.setGeometry(QtCore.QRect(340, 250, 16, 21))
        self.label_65.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_3)
        self.label_66.setGeometry(QtCore.QRect(340, 280, 16, 21))
        self.label_66.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.tab_3)
        self.label_67.setGeometry(QtCore.QRect(90, 320, 161, 21))
        self.label_67.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_67.setObjectName("label_67")
        self.label_52 = QtWidgets.QLabel(self.tab_3)
        self.label_52.setGeometry(QtCore.QRect(340, 190, 47, 14))
        self.label_52.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_52.setObjectName("label_52")
        self.lcdNumber_27 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_27.setGeometry(QtCore.QRect(50, 350, 71, 31))
        self.lcdNumber_27.setStyleSheet("")
        self.lcdNumber_27.setObjectName("lcdNumber_27")
        self.lcdNumber_28 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_28.setGeometry(QtCore.QRect(180, 350, 71, 31))
        self.lcdNumber_28.setStyleSheet("")
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.label_68 = QtWidgets.QLabel(self.tab_3)
        self.label_68.setGeometry(QtCore.QRect(410, 360, 351, 191))
        self.label_68.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("../Pictures/MBE.png"))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName("label_68")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 520, 61, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_69 = QtWidgets.QLabel(self.tab_3)
        self.label_69.setGeometry(QtCore.QRect(40, 500, 47, 14))
        self.label_69.setObjectName("label_69")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_4.setGeometry(QtCore.QRect(40, 520, 42, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_70 = QtWidgets.QLabel(self.tab_3)
        self.label_70.setGeometry(QtCore.QRect(140, 500, 47, 14))
        self.label_70.setObjectName("label_70")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_5.setGeometry(QtCore.QRect(140, 520, 42, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_6.setGeometry(QtCore.QRect(90, 520, 42, 22))
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_71 = QtWidgets.QLabel(self.tab_3)
        self.label_71.setGeometry(QtCore.QRect(70, 480, 221, 16))
        self.label_71.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.tab_3)
        self.label_72.setGeometry(QtCore.QRect(90, 500, 47, 14))
        self.label_72.setObjectName("label_72")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 520, 41, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox_35 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_35.setGeometry(QtCore.QRect(360, 190, 16, 18))
        self.checkBox_35.setText("")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_36.setGeometry(QtCore.QRect(360, 260, 16, 18))
        self.checkBox_36.setText("")
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_37.setGeometry(QtCore.QRect(360, 290, 16, 18))
        self.checkBox_37.setText("")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_38.setGeometry(QtCore.QRect(290, 360, 16, 18))
        self.checkBox_38.setText("")
        self.checkBox_38.setObjectName("checkBox_38")
        self.label_73 = QtWidgets.QLabel(self.tab_3)
        self.label_73.setGeometry(QtCore.QRect(130, 360, 31, 16))
        self.label_73.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_3)
        self.label_74.setGeometry(QtCore.QRect(260, 360, 31, 16))
        self.label_74.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_74.setObjectName("label_74")
        self.checkBox_39 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_39.setGeometry(QtCore.QRect(160, 360, 16, 18))
        self.checkBox_39.setText("")
        self.checkBox_39.setObjectName("checkBox_39")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 40, 71, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.open_setting)

        
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(700, 40, 71, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        
        self.label_75 = QtWidgets.QLabel(self.tab_3)
        self.label_75.setGeometry(QtCore.QRect(440, 70, 161, 21))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.tab_3)
        self.label_76.setGeometry(QtCore.QRect(440, 40, 161, 16))
        self.label_76.setObjectName("label_76")
        self.checkBox_40 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_40.setGeometry(QtCore.QRect(570, 100, 16, 18))
        self.checkBox_40.setText("")
        self.checkBox_40.setObjectName("checkBox_40")
        self.label_77 = QtWidgets.QLabel(self.tab_3)
        self.label_77.setGeometry(QtCore.QRect(460, 100, 91, 16))
        self.label_77.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_3)
        self.label_78.setGeometry(QtCore.QRect(460, 120, 91, 16))
        self.label_78.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.tab_3)
        self.label_79.setGeometry(QtCore.QRect(460, 140, 91, 16))
        self.label_79.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab_3)
        self.label_80.setGeometry(QtCore.QRect(460, 160, 91, 16))
        self.label_80.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.tab_3)
        self.label_81.setGeometry(QtCore.QRect(460, 180, 91, 16))
        self.label_81.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_81.setObjectName("label_81")
        self.checkBox_41 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_41.setGeometry(QtCore.QRect(570, 120, 16, 18))
        self.checkBox_41.setText("")
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_42.setGeometry(QtCore.QRect(570, 140, 16, 18))
        self.checkBox_42.setText("")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_43.setGeometry(QtCore.QRect(570, 160, 16, 18))
        self.checkBox_43.setText("")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_44.setGeometry(QtCore.QRect(570, 180, 16, 18))
        self.checkBox_44.setText("")
        self.checkBox_44.setObjectName("checkBox_44")
        self.label_82 = QtWidgets.QLabel(self.tab_3)
        self.label_82.setGeometry(QtCore.QRect(440, 210, 161, 21))
        self.label_82.setObjectName("label_82")
        self.dial = QtWidgets.QDial(self.tab_3)
        self.dial.setGeometry(QtCore.QRect(50, 420, 50, 64))
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(self.tab_3)
        self.dial_2.setGeometry(QtCore.QRect(150, 420, 50, 64))
        self.dial_2.setObjectName("dial_2")
        self.dial_3 = QtWidgets.QDial(self.tab_3)
        self.dial_3.setGeometry(QtCore.QRect(320, 420, 50, 64))
        self.dial_3.setObjectName("dial_3")
        self.dial_4 = QtWidgets.QDial(self.tab_3)
        self.dial_4.setGeometry(QtCore.QRect(230, 420, 50, 64))
        self.dial_4.setObjectName("dial_4")
        self.label_83 = QtWidgets.QLabel(self.tab_3)
        self.label_83.setGeometry(QtCore.QRect(100, 390, 161, 21))
        self.label_83.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_83.setObjectName("label_83")
        self.lcdNumber_29 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_29.setGeometry(QtCore.QRect(20, 440, 31, 21))
        self.lcdNumber_29.setStyleSheet("")
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.lcdNumber_30 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_30.setGeometry(QtCore.QRect(110, 440, 31, 21))
        self.lcdNumber_30.setStyleSheet("")
        self.lcdNumber_30.setObjectName("lcdNumber_30")
        self.lcdNumber_31 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_31.setGeometry(QtCore.QRect(200, 440, 31, 21))
        self.lcdNumber_31.setStyleSheet("")
        self.lcdNumber_31.setObjectName("lcdNumber_31")
        self.lcdNumber_32 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_32.setGeometry(QtCore.QRect(290, 440, 31, 21))
        self.lcdNumber_32.setStyleSheet("")
        self.lcdNumber_32.setObjectName("lcdNumber_32")
        self.label_84 = QtWidgets.QLabel(self.tab_3)
        self.label_84.setGeometry(QtCore.QRect(20, 420, 41, 16))
        self.label_84.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.tab_3)
        self.label_85.setGeometry(QtCore.QRect(100, 420, 51, 16))
        self.label_85.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.tab_3)
        self.label_86.setGeometry(QtCore.QRect(200, 420, 51, 16))
        self.label_86.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.tab_3)
        self.label_87.setGeometry(QtCore.QRect(290, 420, 51, 16))
        self.label_87.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_87.setObjectName("label_87")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(620, 240, 71, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.open_setting)
        
        
        self.label_88 = QtWidgets.QLabel(self.tab_3)
        self.label_88.setGeometry(QtCore.QRect(460, 240, 31, 16))
        self.label_88.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_88.setObjectName("label_88")
        self.checkBox_45 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_45.setGeometry(QtCore.QRect(570, 240, 16, 18))
        self.checkBox_45.setText("")
        self.checkBox_45.setObjectName("checkBox_45")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(700, 240, 71, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_89 = QtWidgets.QLabel(self.tab_3)
        self.label_89.setGeometry(QtCore.QRect(460, 260, 31, 16))
        self.label_89.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_89.setObjectName("label_89")
        self.checkBox_46 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_46.setGeometry(QtCore.QRect(570, 260, 16, 18))
        self.checkBox_46.setText("")
        self.checkBox_46.setObjectName("checkBox_46")
        self.label_90 = QtWidgets.QLabel(self.tab_3)
        self.label_90.setGeometry(QtCore.QRect(570, 290, 51, 21))
        self.label_90.setObjectName("label_90")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setGeometry(QtCore.QRect(430, 310, 341, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(620, 140, 71, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.open_setting)

        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(700, 140, 71, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(710, 580, 101, 16))
        self.label_51.setObjectName("label_51")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 22))
        self.menubar.setObjectName("menubar")
        self.menuSTM_MBE = QtWidgets.QMenu(self.menubar)
        self.menuSTM_MBE.setObjectName("menuSTM_MBE")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMBE_STM = QtWidgets.QAction(MainWindow)
        self.actionMBE_STM.setObjectName("actionMBE_STM")
        self.actionMBE = QtWidgets.QAction(MainWindow)
        self.actionMBE.setObjectName("actionMBE")
        self.actionSTM = QtWidgets.QAction(MainWindow)
        self.actionSTM.setObjectName("actionSTM")
        self.actionMBE_2 = QtWidgets.QAction(MainWindow)
        self.actionMBE_2.setObjectName("actionMBE_2")
        self.actionLab_camera = QtWidgets.QAction(MainWindow)
        self.actionLab_camera.setObjectName("actionLab_camera")
        self.actionCommand = QtWidgets.QAction(MainWindow)
        self.actionCommand.setObjectName("actionCommand")
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setObjectName("actionOutput")
        self.menuSTM_MBE.addAction(self.actionMBE_STM)
        self.menuSTM_MBE.addAction(self.actionMBE)
        self.menuSTM_MBE.addAction(self.actionSTM)
        self.menuSTM_MBE.addAction(self.actionLab_camera)
        self.menuControl.addAction(self.actionMBE_2)
        self.menuControl.addAction(self.actionCommand)
        self.menuSetting.addAction(self.actionInput)
        self.menuSetting.addAction(self.actionOutput)
        self.menubar.addAction(self.menuSTM_MBE.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_33.setText(_translate("MainWindow", "Combivac CM 52 (2)"))
        self.label_43.setText(_translate("MainWindow", "Eurotherm 3408 (BaF2)"))
        self.label_24.setText(_translate("MainWindow", "MBE line"))
        self.label_31.setText(_translate("MainWindow", "Lake shore 336"))
        self.label_3.setText(_translate("MainWindow", "T3"))
        self.pushButton_2.setText(_translate("MainWindow", "Live plot"))
        self.label_37.setText(_translate("MainWindow", "mbar"))
        self.label_46.setText(_translate("MainWindow", "TDK-lambda (Sn)"))
        self.label_41.setText(_translate("MainWindow", "FUG-MCP 300 (2)"))
        self.label_7.setText(_translate("MainWindow", "K"))
        self.label_42.setText(_translate("MainWindow", "Eurotherm 3408 (Sn)"))
        self.label_27.setText(_translate("MainWindow", "MBE"))
        self.label_21.setText(_translate("MainWindow", "STM"))
        self.label_13.setText(_translate("MainWindow", "Get historical data for the last:"))
        self.label_11.setText(_translate("MainWindow", "GGS"))
        self.label_18.setText(_translate("MainWindow", "Temperatures"))
        self.label_4.setText(_translate("MainWindow", "T4"))
        self.label_8.setText(_translate("MainWindow", "K"))
        self.label_38.setText(_translate("MainWindow", "Load lock"))
        self.label_44.setText(_translate("MainWindow", "Eurotherm 3408 (Co)"))
        self.label_48.setText(_translate("MainWindow", "TDK-lambda (Co)"))
        self.label_15.setText(_translate("MainWindow", "Minutes"))
        self.label_49.setText(_translate("MainWindow", "TDK-lambda (Fe)"))
        self.label_22.setText(_translate("MainWindow", "STM line"))
        self.label_32.setText(_translate("MainWindow", "Combivac CM 52 (1)"))
        self.label_9.setText(_translate("MainWindow", "K"))
        self.label_20.setText(_translate("MainWindow", "Connections status"))
        self.label_5.setText(_translate("MainWindow", "K"))
        self.label_29.setText(_translate("MainWindow", "mbar"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.label_10.setText(_translate("MainWindow", "JT"))
        self.label_6.setText(_translate("MainWindow", "K"))
        self.label_19.setText(_translate("MainWindow", "Pressures"))
        self.label_12.setText(_translate("MainWindow", "K"))
        self.label_2.setText(_translate("MainWindow", "T2"))
        self.label_34.setText(_translate("MainWindow", "NIOPS-06 (1)"))
        self.label_45.setText(_translate("MainWindow", "Eurotherm 3408 (Fe)"))
        self.label_35.setText(_translate("MainWindow", "NIOPS-06 (2)"))
        self.label_47.setText(_translate("MainWindow", "TDK-lambda (BaF2)"))
        self.label_40.setText(_translate("MainWindow", "FUG-MCP 300 (1)"))
        self.label_36.setText(_translate("MainWindow", "Inficon vgc501"))
        self.label_50.setText(_translate("MainWindow", "Thyracont"))
        self.label.setText(_translate("MainWindow", "T1"))
        self.label_26.setText(_translate("MainWindow", "mbar"))
        self.label_16.setText(_translate("MainWindow", "Seconds"))
        self.label_25.setText(_translate("MainWindow", "mbar"))
        self.label_30.setText(_translate("MainWindow", "mbar"))
        self.label_14.setText(_translate("MainWindow", "Hours"))
        self.label_23.setText(_translate("MainWindow", "TLC-500"))
        self.label_53.setText(_translate("MainWindow", "Pressure gauge (1)"))
        self.label_54.setText(_translate("MainWindow", "Pressure gauge (2)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main view"))
        self.label_55.setText(_translate("MainWindow", "Pressure"))
        self.label_56.setText(_translate("MainWindow", "MBE"))
        self.label_57.setText(_translate("MainWindow", "mbar"))
        self.label_58.setText(_translate("MainWindow", "MBE line"))
        self.label_59.setText(_translate("MainWindow", "mbar"))
        self.label_60.setText(_translate("MainWindow", "Load lock"))
        self.label_61.setText(_translate("MainWindow", "mbar"))
        self.label_62.setText(_translate("MainWindow", "Effusion Cells Temperatures"))
        self.label_63.setText(_translate("MainWindow", "Pre-programmed routines"))
        self.label_64.setText(_translate("MainWindow", "Power supply status"))
        self.label_65.setText(_translate("MainWindow", "V"))
        self.label_66.setText(_translate("MainWindow", "A"))
        self.label_67.setText(_translate("MainWindow", "Beam Flux Monitor"))
        self.label_52.setText(_translate("MainWindow", "K"))
        self.pushButton_3.setText(_translate("MainWindow", "Live plot"))
        self.label_69.setText(_translate("MainWindow", "Hours"))
        self.label_70.setText(_translate("MainWindow", "Seconds"))
        self.label_71.setText(_translate("MainWindow", "Get historical data for the last:"))
        self.label_72.setText(_translate("MainWindow", "Minutes"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.label_73.setText(_translate("MainWindow", "mB"))
        self.label_74.setText(_translate("MainWindow", "mA"))
        self.pushButton_5.setText(_translate("MainWindow", "Settings"))
        self.pushButton_6.setText(_translate("MainWindow", "RUN"))
        self.label_75.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Degassing of:</span></p></body></html>"))
        self.label_76.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Beam Flux Calibration</span></p></body></html>"))
        self.label_77.setText(_translate("MainWindow", "Sample Holder"))
        self.label_78.setText(_translate("MainWindow", "Cell A (Sn)"))
        self.label_79.setText(_translate("MainWindow", "Cell B (BeF2)"))
        self.label_80.setText(_translate("MainWindow", "Cell C (Co)"))
        self.label_81.setText(_translate("MainWindow", "Cell D (Fe)"))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Growth</span></p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "Shutter Positions"))
        self.label_84.setText(_translate("MainWindow", "A (Sn)"))
        self.label_85.setText(_translate("MainWindow", "B (BeF2)"))
        self.label_86.setText(_translate("MainWindow", "C (Co)"))
        self.label_87.setText(_translate("MainWindow", "D (Fe)"))
        self.pushButton_13.setText(_translate("MainWindow", "Settings"))
        self.label_88.setText(_translate("MainWindow", "CoSn"))
        self.pushButton_14.setText(_translate("MainWindow", "RUN"))
        self.label_89.setText(_translate("MainWindow", "FeSn"))
        self.label_90.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Status</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Settings"))
        self.pushButton_8.setText(_translate("MainWindow", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "MBE"))
        self.label_51.setText(_translate("MainWindow", "Nanoscale GUI V0.1"))
        self.menuSTM_MBE.setTitle(_translate("MainWindow", "Status"))
        self.menuControl.setTitle(_translate("MainWindow", "Control"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionMBE_STM.setText(_translate("MainWindow", "MBE+STM"))
        self.actionMBE.setText(_translate("MainWindow", "MBE"))
        self.actionSTM.setText(_translate("MainWindow", "STM"))
        self.actionMBE_2.setText(_translate("MainWindow", "MBE"))
        self.actionLab_camera.setText(_translate("MainWindow", "Lab camera"))
        self.actionCommand.setText(_translate("MainWindow", "Command"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionOutput.setText(_translate("MainWindow", "Output"))

    def open_setting(self):
        self._new_window = QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow_2()
        self.ui.setupUi(self._new_window)
        self._new_window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

